site_name: HTTPX
site_description: A next-generation HTTP client for Python.
site_url: https://www.python-httpx.org/

theme:
  name: "material"
  language: "ja"

repo_name: encode/httpx
repo_url: https://github.com/encode/httpx/
edit_uri: ""

nav:
  - はじめに: "index.md"
  - QuickStart: "quickstart.md"
  - Advanced Usage: "advanced.md"
  - Async Support: "async.md"
  - HTTP/2 Support: "http2.md"
  - Environment Variables: "environment_variables.md"
  - Requests Compatibility: "compatibility.md"
  - Developer Interface: "api.md"
  - Exceptions: "exceptions.md"
  - Troubleshooting: "troubleshooting.md"
  - Third Party Packages: "third_party_packages.md"
  - Contributing: "contributing.md"
  - Code of Conduct: "code_of_conduct.md"

markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - css/custom.css
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.css

extra_javascript:
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js
  # - https://unpkg.com/browse/mermaid@8.8.0/dist/mermaid.min.js

  - "js/chat.js"
  - "js/sidecar-1.5.0.js"
